#!python
#
# This file is part of the Crystallographic Data Toolkit and
# distributed under the CeCILL-C licence. See the file LICENCE
# for the full text of this licence.
#
# Written by Konrad Hinsen.
#

from CDTK.MMCIF import MMCIFStructureFactorData
import cPickle
import os
import sys
import getopt

usage = """Usage: convert_mmcif_reflections [options] mmcif_sf_file pickle_file

mmcif_sf_file must be an mmCIF file containing structure factors.
pickle_file is the name of the output file, which will be a cPickle
dump of a tuple of three objects: a ReflectionSet object, an
ExperimentalAmplitudes object containing the experimental scatterig
amplitudes, and a StructureFactor object containing the structure factor
calculated from the fitted model as contained in the mmCIF file. If the
file contains no model structure factor, the last element of the tuple
is None. Note that the experimental data is always stored in the form of
amplitudes, even if the mmCIF file contains intensities instead.

Options:

 --mmcif_complement=file_name
    The specified mmCIF file is read and used as a source for data missing
    in the reflection file. This is required if the reflection file lacks
    symmetry or unit cell data. In that case, the mmCIF file containing
    the structure itself should be specified as a complement.
"""


try:
    options, file_args = getopt.getopt(sys.argv[1:], '', ['mmcif_complement='])
except getopt.GetoptError:
    sys.stderr.write(usage)
    raise SystemExit

if len(file_args) != 2:
    sys.stderr.write(usage)
    raise SystemExit
    
complement_file = None
for option, value in options:
    if option == '--mmcif_complement':
        complement_file = value

for filename in [file_args[0], complement_file]:
    if filename is not None:
        if not os.path.exists(filename):
            sys.stderr.write("File %s not found.\n" % filename)
            raise SystemExit

data = MMCIFStructureFactorData(file_args[0], complement_file)

pickle_file = file(file_args[1], 'wb')
cPickle.dump((data.reflections, data.data, data.model),
             pickle_file)
pickle_file.close()

# *--python-mode--*
